update: ensure exit status

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -30,4 +30,8 @@ jobs:
         wget https://raw.githubusercontent.com/aKqir24/.files/main/Pictures/Wallpapers/wallpaper.jpg -O "$HOME/Pictures/Wallpapers/wallpaper.jpg"
     - name: Test the program
       run: |
-        bash walset.sh --load --verbose && exit 0
+        if [ $? -eq 0 ]; then 
+          time bash walset.sh --load --verbose
+        else  
+          echo "Program failed!"
+        fi
